### ISSUE TITLE
Parquet-thrift compile issue with 0.9.2.

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1729]
Thrift 0.9.2 removed [`setReadLength`](https://github.com/apache/thrift/commit/2ca9c2028593782621c8876817d8772aa5f46ac7). This causes parquet-thrift to fail because it is called for TBinaryProtocol. The reason we use it is defensive: a size is read from the data and then that many bytes are read, so using this method sets a maximum and causes an exception rather than a strange failure later on. The code also has a comment that says it is okay when it can't be used.

```Java
    /* Reduce the chance of OOM when data is corrupted. When readBinary is called on TBinaryProtocol, it reads the length of the binary first,
     so if the data is corrupted, it could read a big integer as the length of the binary and therefore causes OOM to happen.
     Currently this fix only applies to TBinaryProtocol which has the setReadLength defined.
      */
    if (protocol instanceof TBinaryProtocol) {
      ((TBinaryProtocol)protocol).setReadLength(record.getLength());
    }
```

I think the fix is to remove the section above.

**Reporter**: [Ryan Blue](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rdblue) / @rdblue

<sub>**Note**: *This issue was originally created as [PARQUET-180](https://issues.apache.org/jira/browse/PARQUET-180). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-180?#comment-14307649) / @rdblue:
Fixed in [PR #118](https://github.com/apache/incubator-parquet-mr/pull/118). The reason to remove it now is to avoid linker errors if thrift 0.9.1 or later is found in the classpath. Other than this problem, updating to 0.9.2 builds and passes tests.

**Comment by asfimport** [comment]
[Julien Le Dem](https://issues.apache.org/jira/browse/PARQUET-180?#comment-14307743) / @julienledem:
The trouble is that data corruption issues in Thrift will produce hard-to-debug OOM errors.
Another option is to lookup whether the method exists through reflection in a static block and set a boolean IS_READ_LENGTH_SETABLE or something equivalent.
Then the block becomes:
```
if ( IS_READ_LENGTH_SETABLE) {
      ((TBinaryProtocol)protocol).setReadLength(record.getLength());
 }
```
and now we won't have linking issues.

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-180?#comment-14307775) / @rdblue:
That works? I didn't think linking was done lazily like that. Either way, we can definitely do this through reflection if it's valuable.

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-180?#comment-14339338) / @rdblue:
I don't think the one-time reflection strategy works. I get compile errors when I build against 0.9.2. Is it safe to build against 0.9.0 or 0.7.0 and assume it works in 0.9.2?

```Java
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project parquet-thrift: Compilation failure
[ERROR] /home/blue/workspace/parquet-mr/parquet-thrift/src/main/java/parquet/hadoop/thrift/ThriftBytesWriteSupport.java:[136,34] cannot find symbol
[ERROR] symbol:   method setReadLength(int)
[ERROR] location: class org.apache.thrift.protocol.TBinaryProtocol
```

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-180?#comment-14339340) / @rdblue:
I could pretty easily add a version that uses a `Method` field to do this with `invoke`, but I don't know that it's a good idea. Is it possible to do this check in another way?

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-180?#comment-14348030) / @rdblue:
I updated the PR to use the one-time reflection strategy. I verified that it is binary compatible with 0.9.2, but cannot be built against 0.9.2.

I'd like to find a better way to introduce this check, maybe one that works with all of the protocols by limiting the ByteBuffer (or whatever) passed to thrift?

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-180?#comment-14357720) / @rdblue:
Issue resolved by pull request 118
<https://github.com/apache/incubator-parquet-mr/pull/118>
