### ISSUE TITLE
ParquetReader reads do not work with Hadoop version 2.8.5

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2764]
`ParquetReader.read() fails with the following exception on parquet-mr version 1.13.0 when using hadoop version 2.8.5:`
```java

 java.lang.NoSuchMethodError: 'boolean org.apache.hadoop.fs.FSDataInputStream.hasCapability(java.lang.String)' 


at org.apache.parquet.hadoop.util.HadoopStreams.isWrappedStreamByteBufferReadable(HadoopStreams.java:74) 


at org.apache.parquet.hadoop.util.HadoopStreams.wrap(HadoopStreams.java:49) 


at org.apache.parquet.hadoop.util.HadoopInputFile.newStream(HadoopInputFile.java:69) 


at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:787) 


at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:657) 


at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:162) 


org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:135)
```
 
 
 
From an initial investigation, it looks like HadoopStreams has started using [FSDataInputStream.hasCapability](https://github.com/apache/parquet-mr/blob/master/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/util/HadoopStreams.java#L74) but _FSDataInputStream_ does not have the _hasCapability_ API in [hadoop 2.8.x](https://hadoop.apache.org/docs/r2.8.3/api/org/apache/hadoop/fs/FSDataInputStream.html).

**Reporter**: [Atul Mohan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=a2l) / @a2l007
**Assignee**: [Fokko Driesprong](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fokko) / @Fokko

<sub>**Note**: *This issue was originally created as [PARQUET-2276](https://issues.apache.org/jira/browse/PARQUET-2276). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Gang Wu](https://issues.apache.org/jira/browse/PARQUET-2276?#comment-17712178) / @wgtmac:
It was introduced by this PR: [PARQUET-2134: Fix type checking in HadoopStreams.wrap by 7c00 · Pull Request #951 · apache/parquet-mr (github.com)](https://github.com/apache/parquet-mr/pull/951)

 

[~stevel@apache.org] Do you have any idea?

**Comment by asfimport** [comment]
[Steve Loughran](https://issues.apache.org/jira/browse/PARQUET-2276?#comment-17712325) / @steveloughran:
hadoop 2.8 shipped 5 years ago. trying to build against any version of hadoop 2 cripples you, and as hadoop 2.8 **doesn't even work reliably on java 8**,

What exactly are you trying to run, and why?

**Comment by asfimport** [comment]
[Atul Mohan](https://issues.apache.org/jira/browse/PARQUET-2276?#comment-17712575) / @a2l007:
Our community is making an effort to move towards hadoop 3.3.x but it is a bit challenging currently since we have several users currently on 2.8.x who use hadoop map reduce tasks to ingest parquet data. 
Is there any 2.x version that works with Parquet version 1.13.0? If not, it would be important to call out in your docs that support for hadoop 2.x has been dropped.

**Comment by asfimport** [comment]
[Gang Wu](https://issues.apache.org/jira/browse/PARQUET-2276?#comment-17712657) / @wgtmac:
The 1.13.0 release does not work with Hadoop 2.x any more. Do you think this is an issue? @gszadovszky `[~xinlishang]`

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-2276?#comment-17713635) / @gszadovszky:
I think it is fine to drop support of older systems from time to time. It is unfortunate though, it was not properly advertised in PARQUET-2158 that we did not simply upgrade hadoop version in our build but made it incompatible with hadoop2. 
Meanwhile, I think it is fine to re-add support for hadoop2 if it is practically feasible and won't break the hadoop3 support.

**Comment by asfimport** [comment]
[Xinli Shang](https://issues.apache.org/jira/browse/PARQUET-2276?#comment-17715304) / @shangxinli:
@a2l007 Did you try Hadoop 2.9.x? 

I agree with @gszadovszky. Let's find a way to add back the support hadoop2. Parquet is widely used by so many companies and breaking change means big to the industry.  We should have made it clear when taking the breaking changes like this.  @a2l007 Do you think you can work on it?

**Comment by asfimport** [comment]
[Fokko Driesprong](https://issues.apache.org/jira/browse/PARQUET-2276?#comment-17716304) / @Fokko:
@a2l007 I also noticed after the release that we broke compatibility with Hadoop <=2.8. I recently added a CI to check if we're still okay with [Hadoop 2.9\|[https://github.com/apache/parquet-mr/pull/1083].] This will be backported to 1.13.1 as well. Maybe an upgrade from 2.8 to 2.9 is easier than to Hadoop 3. WDYT?

**Comment by asfimport** [comment]
[Atul Mohan](https://issues.apache.org/jira/browse/PARQUET-2276?#comment-17716798) / @a2l007:
@Fokko [~shangx@uber.com] I'll start a discussion in the Druid community regarding this. We'll need to evaluate if the benefits of migrating to parquet version 1.13.1 outweighs the effort needed to bump the default hadoop version to 2.9

**Comment by asfimport** [comment]
[Steve Loughran](https://issues.apache.org/jira/browse/PARQUET-2276?#comment-17718203) / @steveloughran:
@a2l007 really? hadoop 2.8? why haven't they upgraded yet? that is a long way behind on any form of security updates, doesn't come with any guarantees of java8+ support etc. Even hadoop 2.9.x only gets CVE updates for hadoop's own code so that those people running their own clusters with private hadoop-2 forks know what to pick up.

The PARQUET-2134 patch did not break Hadoop 2 compatibility; it used APIs it's which were in the version of Hadoop that parquet compiled against. What it did do was "explicitly break compatibility with a version of hadoop older than the one parquet was built against" That patch may have been the one to show the problem but the reality is there are many other places where incompatibilities could've surfaced.

If you actually want to support hadoop-2.8.5 then the pom needs to be downgraded before anything else.

You also need to worry about Java8/7 compatibility. We're already in a problem where some of the java.nio classes in the java8 SDKs you can get have added more overridden bytebuffer methods then were in the original Oracle Java8, and https algorithms I've been another moving target. so even within "java8" there is "original java8" and the openjdk/corretto/azul versions. Well you can get away with building a modern library with a recent open JDK build, if you really are planning on supporting hadoop 2.8 suddenly all these issues surface. [I know this as when i have to go near the hadoop-2 line i have to use a docker image with java7/, and since moving to macbook m1 I can't do that any more.
