### ISSUE TITLE
Upgrade Hadoop dependency to version 3.2.0

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2695]
Parquet still builds against Hadoop 2.10. This is very out of date and does not work with java 11, let alone later releases.

Upgrading the dependency to Hadoop 3.2.0 makes the release compatible with java 11, and lines up with active work on  HADOOP-18287,  _Provide a shim library for modern FS APIs_ 

This will significantly speed up access to columnar data, especially  in cloud stores.

**Reporter**: [Steve Loughran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stevel@apache.org) / @steveloughran
#### Related issues:
- [Provide a shim library for modern FS APIs](https://issues.apache.org/jira/browse/HADOOP-18287) (relates to)
- [remove deprecated PathGlobPattern and DeprecatedFieldProjectionFilter to compile on hadoop 3.2+](https://issues.apache.org/jira/browse/PARQUET-2165) (relates to)
- [GlobPattern regex library has performance issues with wildcard characters](https://issues.apache.org/jira/browse/HADOOP-12436) (relates to)

<sub>**Note**: *This issue was originally created as [PARQUET-2158](https://issues.apache.org/jira/browse/PARQUET-2158). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Steve Loughran](https://issues.apache.org/jira/browse/PARQUET-2158?#comment-17553552) / @steveloughran:
build is broken by  HADOOP-12436


```Java

Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project parquet-thrift: Compilation failure
Error:  /home/runner/work/parquet-mr/parquet-mr/parquet-thrift/src/main/java/org/apache/parquet/thrift/projection/deprecated/PathGlobPattern.java:[55,49] incompatible types: com.google.re2j.Pattern cannot be converted to java.util.regex.Pattern
```

That was a change to a class believed to be private; clearly not.
