### ISSUE TITLE
parquet-cli not working in release 1.12.0

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2630]
When I run parquet-cli getting  java.lang.NoSuchMethodError

Steps to repdouce:
1. Download parquet-mr 1.12.0 from <https://github.com/apache/parquet-mr/archive/refs/tags/apache-parquet-1.12.0.tar.gz>
1. Build and install using mvn clean install
1. cd parquet-cli
1. `mvn dependency:copy-dependencies`
1. `java -cp 'target/*:target/dependency/*' org.apache.parquet.cli.Main head <parquet file>`
1. Got below exception
   
   WARNING: An illegal reflective access operation has occurred
    WARNING: Illegal reflective access by org.apache.hadoop.security.authentication.util.KerberosUtil ([file:/home/amsundar/hgroot/parquet-mr-apache-parquet-1.12.0/parquet-cli/target/dependency/hadoop-auth-2.10.1.jar\|file://home/amsundar/hgroot/parquet-mr-apache-parquet-1.12.0/parquet-cli/target/dependency/hadoop-auth-2.10.1.jar]) to method sun.security.krb5.Config.getInstance()
    WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    WARNING: All illegal access operations will be denied in a future release
    Exception in thread "main" java.lang.NoSuchMethodError: org.apache.parquet.avro.AvroSchemaConverter.convert(Lorg/apache/parquet/schema/MessageType;)Lorg/apache/avro/Schema;
    at org.apache.parquet.cli.util.Schemas.fromParquet(Schemas.java:89)
    at org.apache.parquet.cli.BaseCommand.getAvroSchema(BaseCommand.java:405)
    at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:66)
    at org.apache.parquet.cli.Main.run(Main.java:155)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
    at org.apache.parquet.cli.Main.main(Main.java:185)
   
    
   
    

**Reporter**: [Akshay Sundarraj](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=akshaysu)
#### Original Issue Attachments:
- [sample.parquet](https://issues.apache.org/jira/secure/attachment/13030721/sample.parquet)
- [sample.schema](https://issues.apache.org/jira/secure/attachment/13030722/sample.schema)

<sub>**Note**: *This issue was originally created as [PARQUET-2065](https://issues.apache.org/jira/browse/PARQUET-2065). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-2065?#comment-17381910) / @gszadovszky:
I've checked this with 1.11.0 and is reproducible so not a regression in 1.12.0.

The problem is that in target there are multiple parquet-cli jars are generated. One is a slim jar (parquet-cli-1.12.0.jar) and another one is a fat jar (parquet-cli-1.12.0-runtime.jar) that contains the avro dependency shaded. If all of these jars put on the classpath (target/\*) it can mix up things. So, I would suggest using one specific jar file from the listed ones instead of putting all jars on the classpath from target. The other dependency jars are required.
For example:
```Java

java -cp target/parquet-cli-1.12.0.jar:target/dependency/* org.apache.parquet.cli.Main head <parquet file>
```

**Comment by asfimport** [comment]
[Akshay Sundarraj](https://issues.apache.org/jira/browse/PARQUET-2065?#comment-17381968):
@gszadovszky  Thanks for the reply.

I tried the new command suggested by you, even though now NoSuchMethodError is resolved I'm getting a different error.

`java -cp target/parquet-cli-1.12.0.jar:target/dependency/* org.apache.parquet.cli.Main head sample.parquet`


java.lang.RuntimeException: Failed on record 0
 at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:86)
 at org.apache.parquet.cli.Main.run(Main.java:155)
 at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
 at org.apache.parquet.cli.Main.main(Main.java:185)
Caused by: **java.lang.ClassCastException: required int32 element is not a group**
 at org.apache.parquet.schema.Type.asGroupType(Type.java:248)
 at org.apache.parquet.avro.AvroRecordConverter.newConverter(AvroRecordConverter.java:284)
 at org.apache.parquet.avro.AvroRecordConverter.newConverter(AvroRecordConverter.java:228)
 at org.apache.parquet.avro.AvroRecordConverter.access$100(AvroRecordConverter.java:74)
 at org.apache.parquet.avro.AvroRecordConverter$AvroCollectionConverter$ElementConverter.<init>(AvroRecordConverter.java:539)


I'm attaching the sample.parquet and parquet schema.

Is it related to https://issues.apache.org/jira/browse/PARQUET-1527?
